In [91]:
pip install mlflow dagshub

Requirement already satisfied: mlflow in /usr/local/lib/python3.12/dist-packages (3.12.0)
Requirement already satisfied: dagshub in /usr/local/lib/python3.12/dist-packages (0.7.0)
Requirement already satisfied: mlflow-skinny==3.12.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.12.0)
Requirement already satisfied: mlflow-tracing==3.12.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.12.0)
Requirement already satisfied: Flask-CORS<7 in /usr/local/lib/python3.12/dist-packages (from mlflow) (6.0.2)
Requirement already satisfied: Flask<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.1.3)
Requirement already satisfied: aiohttp<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.13.5)
Requirement already satisfied: alembic!=1.10.0,<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.18.4)
Requirement already satisfied: cryptography<47,>=43.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (43.0.3)
Requirement already satisfied: docker<8,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (7.1.0)
Requirement already satisfied: graphene<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.4.3)
Requirement already satisfied: gunicorn<26 in /usr/local/lib/python3.12/dist-packages (from mlflow) (25.3.0)
Requirement already satisfied: huey<3,>=2.5.4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.6.0)
Requirement already satisfied: matplotlib<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.10.0)
Requirement already satisfied: numpy<3 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.0.2)
Requirement already satisfied: pandas<3 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.2.2)
Requirement already satisfied: pyarrow<24,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (18.1.0)
Requirement already satisfied: scikit-learn<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.6.1)
Requirement already satisfied: scipy<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.16.3)
Requirement already satisfied: skops<1 in /usr/local/lib/python3.12/dist-packages (from mlflow) (0.14.0)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.0.49)
Requirement already satisfied: cachetools<8,>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.12.0->mlflow) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.12.0->mlflow) (8.3.3)
Requirement already satisfied: cloudpickle<4 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.12.0->mlflow) (3.1.2)
Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.12.0->mlflow) (0.109.0)
Requirement already satisfied: fastapi<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.12.0->mlflow) (0.136.1)
Requirement already satisfied: gitpython<4,>=3.1.9 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.12.0->mlflow) (3.1.47)
Requirement already satisfied: importlib_metadata!=4.7.0,<10,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.12.0->mlflow) (8.7.1)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.12.0->mlflow) (1.38.0)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.12.0->mlflow) (1.38.0)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.12.0->mlflow) (1.38.0)
Requirement already satisfied: packaging<27 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.12.0->mlflow) (26.1)
Requirement already satisfied: protobuf<8,>=3.12.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.12.0->mlflow) (5.29.6)
Requirement already satisfied: pydantic<3,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.12.0->mlflow) (2.12.3)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.12.0->mlflow) (1.2.2)
Requirement already satisfied: pyyaml<7,>=5.1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.12.0->mlflow) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.12.0->mlflow) (2.32.4)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.12.0->mlflow) (0.5.5)
Requirement already satisfied: starlette<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.12.0->mlflow) (0.52.1)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.12.0->mlflow) (4.15.0)
Requirement already satisfied: uvicorn<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.12.0->mlflow) (0.46.0)
Requirement already satisfied: appdirs>=1.4.4 in /usr/local/lib/python3.12/dist-packages (from dagshub) (1.4.4)
Requirement already satisfied: httpx>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (0.28.1)
Requirement already satisfied: rich>=13.1.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (13.9.4)
Requirement already satisfied: dacite~=1.6.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (1.6.0)
Requirement already satisfied: tenacity>=8.2.2 in /usr/local/lib/python3.12/dist-packages (from dagshub) (9.1.4)
Requirement already satisfied: gql[requests] in /usr/local/lib/python3.12/dist-packages (from dagshub) (4.0.0)
Requirement already satisfied: dataclasses-json in /usr/local/lib/python3.12/dist-packages (from dagshub) (0.6.7)
Requirement already satisfied: treelib>=1.6.4 in /usr/local/lib/python3.12/dist-packages (from dagshub) (1.8.0)
Requirement already satisfied: pathvalidate>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (3.3.1)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from dagshub) (2.9.0.post0)
Requirement already satisfied: boto3 in /usr/local/lib/python3.12/dist-packages (from dagshub) (1.43.9)
Requirement already satisfied: semver in /usr/local/lib/python3.12/dist-packages (from dagshub) (3.0.4)
Requirement already satisfied: dagshub-annotation-converter>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (0.2.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (1.23.0)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic!=1.10.0,<2->mlflow) (1.3.11)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography<47,>=43.0.0->mlflow) (2.0.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from dagshub-annotation-converter>=0.2.0->dagshub) (6.1.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from dagshub-annotation-converter>=0.2.0->dagshub) (11.3.0)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from docker<8,>=4.0.0->mlflow) (2.5.0)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.1.8)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.12.0->mlflow) (4.0.12)
Requirement already satisfied: graphql-core<3.3,>=3.1 in /usr/local/lib/python3.12/dist-packages (from graphene<4->mlflow) (3.2.8)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in /usr/local/lib/python3.12/dist-packages (from graphene<4->mlflow) (3.2.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.23.0->dagshub) (0.16.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (1.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (3.3.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3->mlflow) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3->mlflow) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->dagshub) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.1.0->dagshub) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.1.0->dagshub) (2.20.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow) (3.6.0)
Requirement already satisfied: prettytable>=3.9 in /usr/local/lib/python3.12/dist-packages (from skops<1->mlflow) (3.17.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.4.0)
Requirement already satisfied: botocore<1.44.0,>=1.43.9 in /usr/local/lib/python3.12/dist-packages (from boto3->dagshub) (1.43.9)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from boto3->dagshub) (1.1.0)
Requirement already satisfied: s3transfer<0.18.0,>=0.17.0 in /usr/local/lib/python3.12/dist-packages (from boto3->dagshub) (0.17.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json->dagshub) (3.26.2)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json->dagshub) (0.9.0)
Requirement already satisfied: backoff<3.0,>=1.11.1 in /usr/local/lib/python3.12/dist-packages (from gql[requests]->dagshub) (2.2.1)
Requirement already satisfied: requests_toolbelt<2,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from gql[requests]->dagshub) (1.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography<47,>=43.0.0->mlflow) (3.0)
Requirement already satisfied: google-auth~=2.0 in /usr/local/lib/python3.12/dist-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.12.0->mlflow) (2.47.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.12.0->mlflow) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.12.0->mlflow) (0.0.4)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.12.0->mlflow) (5.0.3)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib_metadata!=4.7.0,<10,>=3.7.0->mlflow-skinny==3.12.0->mlflow) (3.23.1)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.1.0->dagshub) (0.1.2)
Requirement already satisfied: opentelemetry-semantic-conventions==0.59b0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.12.0->mlflow) (0.59b0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prettytable>=3.9->skops<1->mlflow) (0.6.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.12.0->mlflow) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.12.0->mlflow) (2.41.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.12.0->mlflow) (3.4.7)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from typing-inspect<1,>=0.4.0->dataclasses-json->dagshub) (1.1.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.12.0->mlflow) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.12.0->mlflow) (4.9.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.12.0->mlflow) (0.6.3)

In [92]:
!pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)

### Set Mlflow

In [93]:
import dagshub
dagshub.init(repo_owner='iamdebasishdas123', repo_name='YouTube-Mood-Tracker', mlflow=True)
import mlflow

Initialized MLflow to track repo "iamdebasishdas123/YouTube-Mood-Tracker"

Repository iamdebasishdas123/YouTube-Mood-Tracker initialized!

## Load Dataset

In [94]:
import numpy as np
import pandas as pd

In [95]:
df = pd.read_csv('https://raw.githubusercontent.com/Himanshu-1703/reddit-sentiment-analysis/refs/heads/main/data/reddit.csv')
df.head()

                                       clean_comment  category
0   family mormon have never tried explain them t...         1
1  buddhism has very much lot compatible with chr...         1
2  seriously don say thing first all they won get...        -1
3  what you have learned yours and only yours wha...         0
4  for your own benefit you may want read living ...         1

## 1. Preprocessing Data

In [96]:
df.sample(20).to_dict(orient='records')

[{'clean_comment': 'jaan maar denge ', 'category': 0},
 {'clean_comment': 'fuck this shit ragaism coming soon', 'category': -1},
 {'clean_comment': ' mean has number indianfood using cbd ', 'category': -1},
 {'clean_comment': ' ', 'category': 0},
 {'clean_comment': ' all wish for this someday ', 'category': 0},
 {'clean_comment': nan, 'category': 0},
 {'clean_comment': 'mitron aur landoor chutyaaa bannaya badda mazza ayya chutya bannayegaaaa aur mazza ayeenge ',
  'category': 0},
 {'clean_comment': ' team ppr bonuses pick one bmarsh mcrabtree chyde mthomas ',
  'category': 0},
 {'clean_comment': 'banda bundaas hain his speech was virat kohli hitting triple',
  'category': 0},
 {'clean_comment': 'shazia ilmi loses 340 votes ', 'category': -1},
 {'clean_comment': 'nepanašu kad daug pastangų įdėjai post pavadinimą galvodamas',
  'category': 0},
 {'clean_comment': 'and when the free encyclopedia the team sports and other news items credits sr33 new delhi the team sports and other news items credits sr33 new delhi the team sports and other news items credits sr33 new delhi the team sports and other news items credits sr33 new delhi the team sports and other news items credits sr33 new delhi the team sports and other news items credits sr33 new delhi the team sports and other news items credits sr33 new delhi the',
  'category': 1},
 {'clean_comment': 'kažkas apdovanojo mane sidabro medaliu ačiū mielas skaitytojui ačiū kitiems kurie mėgsta dėl jūsų pasistengsiu atsiminti dar daugiau istorijų ',
  'category': 0},
 {'clean_comment': 'this newsreader struggling much speak coherently that difficult listen ',
  'category': 1},
 {'clean_comment': 'saved they invented back the days when they were clg ',
  'category': 0},
 {'clean_comment': 'why are the votes counted thought evms give out instand results ',
  'category': 0},
 {'clean_comment': 'jnk could throw big fucking surprise ', 'category': -1},
 {'clean_comment': 'what about rajasthani society that early marriage encouraged much not talking about the child marriages rural areas even cas and lawyers firmly believe that marriage rite passage and that must completed years age for the man and for the woman and what find funny huge chunk these early married rajasthanis are perfectly happy with their lives and not find the increased responsibility burden all ',
  'category': 1},
 {'clean_comment': 'idiots haha', 'category': -1},
 {'clean_comment': ' first post india yogendra yadav told you ',
  'category': 1}]

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37249 entries, 0 to 37248
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   clean_comment  37149 non-null  object
 1   category       37249 non-null  int64
dtypes: int64(1), object(1)
memory usage: 582.1+ KB

In [98]:
df['category'].value_counts()

category
 1    15830
 0    13142
-1     8277
Name: count, dtype: int64

In [99]:
df.duplicated().sum()

np.int64(449)

- Problem of Database
1. backslash in the data
2. Null data arund 100 rows
3. 449 duplicated data
3. Imbalanced data

##### 1.1 Remove NA data

In [100]:
df.dropna(inplace=True)

##### 1.2 Remove Duplicate

In [101]:
df.drop_duplicates(inplace=True)

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 36799 entries, 0 to 37248
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   clean_comment  36799 non-null  object
 1   category       36799 non-null  int64
dtypes: int64(1), object(1)
memory usage: 862.5+ KB

In [103]:
df = df[~(df['clean_comment'].str.strip() == '')]

In [104]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 36793 entries, 0 to 37248
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   clean_comment  36793 non-null  object
 1   category       36793 non-null  int64
dtypes: int64(1), object(1)
memory usage: 862.3+ KB

In [105]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [106]:
# Ensure necessary NLTK data is downloaded
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [107]:
# Define the preprocessing function
def preprocess_comment(comment):
    # Convert to lowercase
    comment = comment.lower()

    # Remove trailing and leading whitespaces
    comment = comment.strip()

    # Remove newline characters
    comment = re.sub(r'\n', ' ', comment)

    # Remove non-alphanumeric characters, except punctuation
    comment = re.sub(r'[^A-Za-z0-9\s!?.,]', '', comment)

    # Remove stopwords but retain important ones for sentiment analysis
    stop_words = set(stopwords.words('english')) - {'not', 'but', 'however', 'no', 'yet'}
    comment = ' '.join([word for word in comment.split() if word not in stop_words])

    # Lemmatize the words
    lemmatizer = WordNetLemmatizer()
    comment = ' '.join([lemmatizer.lemmatize(word) for word in comment.split()])

    return comment

In [108]:
# Apply the preprocessing function to the 'clean_comment' column
df['clean_comment'] = df['clean_comment'].apply(preprocess_comment)

In [109]:
df.sample(20).to_dict(orient='records')

[{'clean_comment': 'rula diya come back 2019 maybe asshats deserve hero need',
  'category': 0},
 {'clean_comment': 'pretty sure direct violation license section iii distribute publicly perform work adaptation collection must provide reasonable medium mean utilizing iii extent reasonably practicable uri licensor specifies associated work',
  'category': 1},
 {'clean_comment': 'cant watch video office hope someone start livebloging',
  'category': 0},
 {'clean_comment': 'fucking manmohan bow front mother sonia namo front mother india spot difference sorry draw parallel dolt resist',
  'category': -1},
 {'clean_comment': 'faasos blaming release piece foreign location based intern already fired',
  'category': -1},
 {'clean_comment': 'muslim used rule entire subcontinent british hmm cogent people certainly',
  'category': 1},
 {'clean_comment': 'hello american came across headline html headline indian state election matter whole world but article nothing describe part anyone maybe give insight modi winning would affect rest world country thought election really curious political situation india like modi right wing guy left wing guy people generally happy people hate even proponent saying opponent also saying thanks feedback',
  'category': 1},
 {'clean_comment': 'theydidthemath', 'category': 0},
 {'clean_comment': 'okay okay practice alone', 'category': 1},
 {'clean_comment': 'mudi say hundred thing nothing case something incompetent gawaar mess call critic pakistani black money wishers think following trump model',
  'category': -1},
 {'clean_comment': 'shitbjpsays notthepyaaz', 'category': 0},
 {'clean_comment': 'election commission finally peace usual voice screaming evms complaint since bjp losing time',
  'category': -1},
 {'clean_comment': 'meanwhile jumlendra modi busy slinging dirt congress baseless allegation',
  'category': 1},
 {'clean_comment': 'imagine owner bakery indian muslim exact circumstance would bakery still open name today',
  'category': 1},
 {'clean_comment': 'minute warning place people', 'category': 0},
 {'clean_comment': 'smell like desperation', 'category': 0},
 {'clean_comment': 'shall pas coming another bank employee lost lot since 8th november money not much but socially physically',
  'category': 1},
 {'clean_comment': 'long term success genetic diversity also essential preferably father child different',
  'category': 1},
 {'clean_comment': 'open bjp handle asking people watch', 'category': 0},
 {'clean_comment': 'build top everything', 'category': 1}]

## 2. Model Building

In [110]:
import mlflow
import mlflow.sklearn
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split, cross_val_predict, StratifiedKFold
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pandas as pd
import matplotlib.pyplot as plt

In [111]:
# Step 1: Vectorize the comments using Bag of Words (CountVectorizer)
vectorizer = CountVectorizer(max_features=5000)  # Bag of Words model with a limit of 5000 features

In [112]:
X = vectorizer.fit_transform(df['clean_comment']).toarray()
y = df['category']  # Assuming 'sentiment' is the target variable (0 or 1 for binary classification)

In [113]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [114]:
X.shape

(36793, 5000)

In [115]:

y = y.map({-1: 0, 0: 1, 1: 2})

In [116]:
y.shape

(36793,)

In [117]:
# Set or create an experiment
mlflow.set_experiment("Test Experiment Youtube Mood Tracker")

<Experiment: artifact_location='mlflow-artifacts:/a919a8ba2f0a451c8fdec499a9ec20b4', creation_time=1778520588352, experiment_id='0', last_update_time=1778520588352, lifecycle_stage='active', name='Test Experiment Youtube Mood Tracker', tags={'mlflow.experimentKind': 'custom_model_development'}, trace_location=None, workspace='default'>

In [118]:
import seaborn as sns

In [119]:
# Step 1: Split the data into training and testing sets (80% train, 20% test)
import matplotlib.pyplot as plt
import mlflow
import mlflow.xgboost  # Crucial for logging XGBoost correctly
import seaborn as sns
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
)
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier

# Step 1: Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Step 2: Define and train an XGBoost baseline model
with mlflow.start_run() as run:
    # Metadata tags
    mlflow.set_tag("mlflow.runName", "XGBoost_Baseline_TrainTestSplit")
    mlflow.set_tag("experiment_type", "baseline")
    mlflow.set_tag("model_type", "XGBClassifier")
    mlflow.set_tag(
        "description",
        "Baseline XGBoost sentiment model using Bag of Words (BoW)",
    )

    # Log vectorizer params
    mlflow.log_param("vectorizer_type", "CountVectorizer")
    mlflow.log_param("vectorizer_max_features", vectorizer.max_features)

    # Model Hyperparameters
    params = {
        "n_estimators": 350,
        "max_depth": 12,
        "learning_rate": 0.1,
        "subsample": 0.8,
        "colsample_bytree": 0.8,
        "random_state": 42,
        "eval_metric": "logloss",
    }
    mlflow.log_params(params)  # Dictionary logging keeps code clean

    # Train model
    model = XGBClassifier(**params)
    model.fit(X_train, y_train)

    # Evaluate
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    mlflow.log_metric("accuracy", accuracy)

    # Classification report logic
    classification_rep = classification_report(y_test, y_pred, output_dict=True)
    for label, metrics in classification_rep.items():
        if isinstance(metrics, dict):
            # Formats keys cleanly as "class_0_precision", "macro_avg_f1-score"
            clean_label = label.replace(" ", "_")
            for metric, value in metrics.items():
                mlflow.log_metric(f"{clean_label}_{metric}", value)

    # Confusion Matrix
    conf_matrix = confusion_matrix(y_test, y_pred)
    plt.figure(figsize=(8, 6))
    sns.heatmap(conf_matrix, annot=True, fmt="d", cmap="Blues")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.title("Confusion Matrix")

    # Consistent local paths to prevent file-not-found errors
    plt.savefig("confusion_matrix.png")
    mlflow.log_artifact("confusion_matrix.png")
    plt.close()  # Close the plot to free memory

    # Native XGBoost logging
    mlflow.xgboost.log_model(model, "xgboost_model")

    # Save data snippet
    df.to_csv("dataset.csv", index=False)
    mlflow.log_artifact("dataset.csv")

print(f"Accuracy: {accuracy}")

2026/05/18 17:22:36 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run XGBoost_Baseline_TrainTestSplit at: https://dagshub.com/iamdebasishdas123/YouTube-Mood-Tracker.mlflow/#/experiments/0/runs/d41936a8fcde4c67b18cfb94565807ff
🧪 View experiment at: https://dagshub.com/iamdebasishdas123/YouTube-Mood-Tracker.mlflow/#/experiments/0
Accuracy: 0.8498437287674956

In [120]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.84      0.69      0.76      1650
           1       0.82      0.97      0.89      2555
           2       0.89      0.84      0.86      3154

    accuracy                           0.85      7359
   macro avg       0.85      0.83      0.83      7359
weighted avg       0.85      0.85      0.85      7359

### Run Experiments

##### 1.1 BOW or TFIDF

- Bag of Word(BOW)
1. It is a NLP technique to create embedding
2. Create unique collection of words from the all documents.
3. Count how many times each word from the master vocabulary appears in a specific document.
4. Represent each document as an array (vector) of these word counts.

- Example
Document 1: "The dog barked at the cat.

Document 2: "The cat sat on the mat."First

compile the unique vocabulary: ['the', 'dog', 'barked', 'at', 'cat', 'sat', 'on', 'mat'] (Total length: 8).

Using BoW, we represent the documents as numerical frequency vectors:

Document 1: \([2, 1, 1, 1, 1, 0, 0, 0]\)

Document 2: \([2, 0, 0, 0, 1, 1, 1, 1]\)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

def compute_bow(corpus, max_features=None):
    """
    Converts a text corpus into a Bag of Words matrix.
    """
    # Initialize the vectorizer
    vectorizer = CountVectorizer(max_features=max_features)
    
    # Learn vocabulary and transform text to sparse matrix
    bow_sparse = vectorizer.fit_transform(corpus)
    
    # Convert to a readable DataFrame with word labels
    feature_names = vectorizer.get_feature_names_out()
    bow_df = pd.DataFrame(bow_sparse.toarray(), columns=feature_names)
    
    return bow_df, vectorizer

- TF-IDF (Term Frequency-Inverse Document Frequency) : TF-IDF (Term Frequency-Inverse Document Frequency) is a foundational natural language processing algorithm that measures how important a word is to a specific document within a collection of text [1, 2]. It significantly improves upon the classic Bag of Words model because it does not just count how often words appear; it penalises words that show up everywhere (like "the", "is", or "and") and rewards unique words that convey actual meaning [1, 2].

1. Term Frequency (TF): Measures how frequently a word appears inside a single document.
2. Inverse Document Frequency (IDF): Measures how unique or rare a word is across your entire collection of documents (corpus).

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

def compute_tfidf(corpus, max_features=None):
    """
    Converts a text corpus into a TF-IDF matrix.
    """
    # Initialize the vectorizer
    vectorizer = TfidfVectorizer(max_features=max_features)
    
    # Learn vocabulary and weights, transform text to sparse matrix
    tfidf_sparse = vectorizer.fit_transform(corpus)
    
    # Convert to a readable DataFrame with word labels
    feature_names = vectorizer.get_feature_names_out()
    tfidf_df = pd.DataFrame(tfidf_sparse.toarray(), columns=feature_names)
    
    return tfidf_df, vectorizer

##### 1.2 Model Selection